### ISSUE TITLE
ContextLogger, AppLogger 需要支持自定义format

### ISSUE THREAD

**Issue by AntiMoron** [eggjs/egg-logger#89]
当涉及到特殊的日志分析系统对接时候，默认的logger无法满足需求。我们知道，文档里有customLogger等方式实现这种场景，但是：

1. customLogger用起来太繁琐了，需要

```javascript
this.ctx.getLogger('xxx').debug('xxxx')
```
不如`this.logger`，并且this.logger不能指定是哪个logger实现

2. 已有大量的log历史工程，如果要改变日志格式需要大量修改代码。从直觉看这个是统一对logger做配置的事情，而不是大量修改工程代码迁移logger的事。因此希望默认logger也能像自定义logger一样支持format
3. 自定义logger时候引入了很多新的配置项工作，默认logger不需要做的配置现在要拿代码亲自指定一遍：文件名、dir等等、等等

**Comment by AntiMoron** [comment]
提议：
配置项内支持默认logger设置format：

```
logger: {
 format: (meta) => {.
    return JSON.stringify(meta);
 }
}

```

**Comment by AntiMoron** [comment]
@fengmk2 @atian25

**Comment by AntiMoron** [comment]
找到办法了，但是莫名其妙的在config里配置，ts会提示异常；
另外官网文档需要更新下使用方法。

**Comment by mingyard** [comment]
> 找到办法了，但是莫名其妙的在config里配置，ts会提示异常； 另外官网文档需要更新下使用方法。

什么办法，请大佬分享一下

**Comment by jiang-zx** [comment]
可惜message是个string，能 any 就好了

> @mingyard https://github.com/eggjs/egg-logger/blob/master/index.d.ts
> 
> 文档写的不太完整，但是有类型定义。看这里，比如contextFormatter、formatter这样的配置项 可以传返回字符串的函数
