### ISSUE TITLE
包含node低版本不支持语法，低版本node直接运行会报错

### ISSUE THREAD

**Issue by fish-jade** [eggjs/egg-logger#96]
https://github.com/eggjs/egg-logger/blob/adbc0c52cdd46cba263f21e92225c624160efdd1/lib/utils.js#L38

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-logger/blob/master/package.json#L52 请升级到 node 14 最新版本

**Comment by bloody-ux** [comment]
> https://github.com/eggjs/egg-logger/blob/adbc0c52cdd46cba263f21e92225c624160efdd1/lib/utils.js#L38

+1

**Comment by fengmk2** [comment]
https://github.com/eggjs/egg-logger/blob/master/package.json#L52 请升级到 node 14 最新版本
